### ISSUE TITLE
请教一下 ios-token

### ISSUE THREAD

**Issue by feng003** [myappcloud/push#1]
报错 “400 Bad Request for BadMessageId” 这个是我的参数传递问题呢？ 还是证书问题呢？想使用一下 有没有问题？

**Comment by feng003** [comment]
报错  “400 Bad Request for BadMessageId”  这个是我的参数传递问题呢？ 还是证书问题呢？

**Comment by myappcloud** [comment]
消息ID要求是 uuid 的格式
